FROM ruby:3.0.6

ENV LANG C.UTF-8
ENV NODE_VERSION 20.12.0

RUN curl -fsSLO --compressed "https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-arm64.tar.xz" \
 && tar -xJf "node-v${NODE_VERSION}-linux-arm64.tar.xz" -C /usr/local --strip-components=1 --no-same-owner \
 && rm "node-v${NODE_VERSION}-linux-arm64.tar.xz" \
 && ln -s /usr/local/bin/node /usr/local/bin/nodejs

#RUN curl -sL https://deb.nodesource.com/setup_11.x | bash -

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    libfontconfig1 \
    vim \
    libmecab2 \
    libmecab-dev \
    mecab \
    mecab-utils \
    mecab-ipadic-utf8 \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir /app

# ワーキングディレクトリの設定
WORKDIR /app

# 旧バージョンのbundlerを利用
RUN gem install bundler -v 2.4.22